services:
  - type: web
    name: screenshot-service
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node backend/server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true