services:
  - type: web
    name: screenshot-service
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production